api Version: v1
kind: Namespace
metadata:
name: liatrio

apiVersion: apps/v1
kind: Deployment
Namespace: liatrio
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: 570396479773.dkr.ecr.us-east-1.amazonaws.com/liatrio-int/app:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
Namespace: liatrio
metadata:
  name: cms-service
spec:
  selector:
    app: cms-deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
